[".zsh/antigen"]
    type = "archive"
    url = "https://github.com/zsh-users/antigen/archive/refs/heads/develop.zip"
    stripComponents = 1
    include = ["*/antigen.zsh", "*/bin/**"]
    refreshPeriod = "168h"
