#! /bin/sh
# colors
for dircolors in gdircolors dircolors ; do
	if command -v $dircolors >/dev/null 2>&1 ; then
		dircolor_text=''
		if [ -f "${HOME}/.dir_colors" ] ; then
			dircolor_text=`cat "${HOME}/.dir_colors"`
		elif [ -f /etc/DIR_COLORS ] ; then
			dircolor_text=`cat /etc/DIR_COLORS`
		fi

		if $dircolors --version 2>/dev/null | grep GNU >/dev/null 2>&1 ; then
			dircolor_text="${dircolor_text}\nSTICKY_OTHER_WRITABLE 01;04;34;40"
			dircolor_text="${dircolor_text}\nOTHER_WRITABLE 01;34;40"
		fi

		eval `echo "${dircolor_text}" | $dircolors -b -`
		break
	fi
done

export EDITOR=vim

FCEDIT=$EDITOR
export FCEDIT
alias cd..='cd ..'

# handles per OS aliases, fixes a few terms
case `uname -s` in
	Linux|CYGWIN*)
		alias ls="ls -h --color=auto"
		alias grep='grep -d skip --color=auto'
	;;
	FreeBSD|Darwin|DragonFly)
		if command -v gls >/dev/null 2>&1 ; then
			alias ls="gls -h --color=auto"
		elif ls --version 2>/dev/null | grep GNU >/dev/null 2>&1 ; then
			alias ls="ls -h --color=auto"
		else
			LSCOLORS="ExGxFxDxCxDxDxHbaDEaEa"
			export LSCOLORS
			alias ls="ls -Gh"
		fi
		alias grep='grep -d skip --color=auto'
	;;
esac

alias ping='ping -c4'
alias ping6='ping6 -c4'
alias week="date '+%Y.%W'"
